### ISSUE TITLE
ERROR: #2: Cannot load class 'MStart': Unable to load class file"

### ISSUE THREAD

**Issue by DarkShadow44** [i-nex/I-Nex#92]
This is a problem on latest Arch Linux. For me the build fails, but it doesn't abort. The class simply isn't compiled, and it errors when trying to start i-nex - with the error in the title.

The underlying compile error is: `Finfosys.class:335: error: Loop variable cannot be global`

But it would also be great to have the build stop when it fails.

I made a fix forArch Linux here: https://gist.github.com/DarkShadow44/eedad25a98fb83b9726d349e51f1426e

**Comment by martinkg** [comment]
I made a patch against the recent master branch for Fedora.
[i-nex-fix-compilation.txt](https://github.com/i-nex/I-Nex/files/3746926/i-nex-fix-compilation.txt)
